### ISSUE TITLE
fix: plainToClass object with type BigNumber

### ISSUE THREAD

**Issue by Natashkinsasha** [typestack/class-transformer#1187]
### Description
Whenever I try to plainToClass any class that contains property: BigNumber - I receive the error "cannot call constructor directly; use BigNumber.from (operation=\"new (BigNumber)\", code=UNSUPPORTED_OPERATION, version=bignumber/5.6.0)", even if this property has no any class-transformer decorators

**Minimal code-snippet showcasing the problem**
```ts
import { BigNumber } from 'ethers';

Class Test {
  test: BigNumber;
}

plainToClass(Test, { test: BigNumber.from(1) })
```

### Expected behavior
Should create object

### Actual behavior
"error": {
           "reason": "cannot call constructor directly; use BigNumber.from",
           "code": "UNSUPPORTED_OPERATION",
           "operation": "new (BigNumber)",
           "name": "Error",
           "message": "cannot call constructor directly; use BigNumber.from (operation=\"new (BigNumber)\", code=UNSUPPORTED_OPERATION, version=bignumber/5.6.0)"
}

**Comment by diffy0712** [comment]
Hello @Natashkinsasha,

`BigNumber` is an `ethers` export, so the support for it is not implemented in `class-transformer` and will not be. 
If you provide a custom Type you can use [custom transformers](https://github.com/typestack/class-transformer?tab=readme-ov-file#additional-data-transformation) to convert it (just like in the example with moment) and provide a simple value in your plain instead of passing the instance (and let class-transformer to do the instantiation).

Closing as invalid. If you have any questions left feel free to comment on this issue.
