### ISSUE TITLE
nullable fields and typescript

### ISSUE THREAD

**Issue by theigor** [typestack/class-transformer#140]
Hi,

I am not sure if this is a bug or a question or me doing something wrong, but if I have a class with a nullable non-string field like so:

```ts
  @Type(() => Number)
  purchase_price?: number;
```

When I run it through `plainToClass` and my json is explicitly `null` like so

```json
{
  "purchase_price": null
}
```

`plainToClass` sets the value of `purchase_price` to `0` instead of `null`.
Now I can "fix" that by specifying a transformer, but I feel like I shouldn't need a transformer just to preserve null values of nullable fields.

```ts
  @Type(() => Number)
  @Transform(v => v || null)
  purchase_price?: number;
```

Am I doing something wrong?

Thanks!

**Comment by MTschannett** [comment]
From the type annotation that you have provided, the conversion is correct. The typescript types are lost after it was transpiled to javascript.

## Example: 
```
() => Number
```
In this code snippet the `Number` uses the [Javascript Class - Number](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number).

The result that you see is the correct behaivior: 
Number(null) => 0

I'm not sure if a nullable number class exists (I couldn't find one on MDN). Maybe we could create such classes ourself, which handle this  in the desired way.

@cojack  What do you think about a NullableNumber class which works like this:

NullableNumber(5) => 5
NullableNumber(null) => null
NullableNumber(3.42343) => 3.42343
NullableNumber("string") => NaN

It could extend the Number class and check for the desired cases otherwise falls back to normal behaivior.

**Comment by NoNameProvided** [comment]
As @MTschannett wrote, the conversion is correct because you explicitly tell the transformer to treat the received value as a number via the `@Type(() => Number)` decorator (`Number(null)` results in `0`).

The `@Type` decorator is mostly for user-defined classes, you don't need to use it for most of the builtin types. 

So your example would look like this: 

```ts
class Example {
  purchase_price?: number;
}

const result = plainToClass(Example, { purchase_price: null }); 
```

This will result in the expected `Example {purchase_price: null}` object.

Please not also the `class-transformer` doesn't care about the nullable operator, it only does data-transformation, if you need validation please take a look at [class-validator][1].

[1]: https://github.com/typestack/class-validator

**Comment by NoNameProvided** [comment]
> @cojack What do you think about a NullableNumber class which works like this:

This is not needed, as this is not a standard behaviour, and we have @Transform already for special use-cases.
