### ISSUE TITLE
fix: class-transformer modifies the prototype of non native objects

### ISSUE THREAD

**Issue by pedroteixeira** [typestack/class-transformer#141]
Hello!

When using the convert function (for ex `plainToClassFromExist`), if there is an immutable-js (for ex) object in the object being processed, the library seem to modify the prototype of the classes of the objects being passed, leading to very weird bugs - hard to track to this library :)

Even using `@Exclude` - I did not manage to avoid this behaviour.

I did not find time to write a reproducible snippet, but wanted to give the heads up - in case it's something already known.

I guess it's easy to reproduce just by passing a `Immutable.List()` (for ex) inside a given js object.
The consequences of the transform I did not look into - but some Immutable prototype functions start malfunctioning.

thanks!

**Comment by godenji** [comment]
Seeing the same in context of Ngrx Observables with Immutable.js List type in some cases. Truly bizarre behavior, like an empty `List()` magically receiving the properties of a class-transformer modified class instance.

Example:
```javascript
// thread.ts
import { List } from 'immutable'

export class Thread {
  @Type(() => UserId)
  participants: List<UserId> = List()
  ...
}

// thread-service.ts
messages(thread: Thread): Observable<List<Message>> {
  const empty = List() // empty list, right?
  console.log('empty?', empty) // non-empty! contains `participants` data
  return this.messages$.map(xs =>
    Message.sort(xs.filter(x => x.threadId === thread._id))
  )
}
```
If I omit the default value for participants (i.e. just define `participants: List<UserId>`) then the data swapping behavior does not occur. Pretty insidious bug, have been falling back to mutable arrays as a workaround.

@pedroteixeira, thanks for posting, only came on this issue by chance -- this has been an absolutely hellacious bug to track down to some root cause :)

**Comment by NoNameProvided** [comment]
This indeed looks bizarre! 

@godenji Can you please provide some more information? How do you use class-transformer? It's not visible from this snippet if you could provide me with a working repro case on Stackblitz that would help a lot! 

@cojack @MTschannett we should prioritize this.

**Comment by NoNameProvided** [comment]
`plainToClassFromExist` is being deprecated and will be removed.
