### ISSUE TITLE
Feature: Provide a common base class to avoid implicit casting issues

### ISSUE THREAD

**Issue by chriskuech** [typestack/class-transformer#1478]
### Description

* I'm frustrated that TypeScript allows implicit casting to a class, despite this being incorrect and not preserving the inheritance chain.
* I'm frustrated that I have to use `plainToInstance` to instantiate a class-transformer type, as the requirement is not enforced by the type system or linters and new contributors never know to do this.
* I'm frustrated that I can't enable `"strictPropertyInitialization": true` to mitigate these because I would have to add a verbose constructor to every class-transformer class in my project.

### Proposed solution

Provide a base class to use for class-transformer types that--
* Provides an obscure method that users wont see but will ensure TS does not allow implicit casting to the class.
* Provides a constructor accepting a parameter of the same shape as the class, so that classes can be defined in a single statement and `"strictPropertyInitialization": true` compiler option can be enabled.

Ex:
```ts
class A extends BaseClass {
  a: number;
}

// enabled
const a = new A({ a: 42 });

// disallowed
const a = new A();

// disallowed
const a: A = { a: 42 };
```

**Comment by bhaugeea** [comment]
Providing a base class with such a constructor does seem like a very good and convenient idea, but I'm not sure it needs to be in the scope of this library. Is there some reason why this kind of feature is particularly tied into this library's architectural concern rather than, say, an ORM or the domain objects themselves?

Although this library does instantiate classes, I don't think of it as performing the factory function in the normal sense at all.

In the _right context_ it's definitely a good idea, and I'm not very proud of myself for generally just turning off the tsconfig flag and not addressing the problem.

**Comment by diffy0712** [comment]
I do think that this should not be handled by this library. The library provides transformers, naming in expose etc, so I do not see that this could be implemented the way you would like to.

I close this as wontfix. If you have any questions left feel free to comment on this issue.
