### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by keenondrums** [typestack/class-transformer#153]
Each instance of class-transformer has its own isolated metadata storage. If several libraries use it or you want to use it or it resolves to different modules for any reason it could make it unusable. Would you be willing to accept a PR which adds DI in a fashion of class-validator?

**Comment by MTschannett** [comment]
Could you please provide a reproduction of this problem. I don't quite understand your problem.

**Comment by NoNameProvided** [comment]
> Each instance of class-transformer has its own isolated metadata storage.

You need to use the same `class-transformer` version across your projects and the metadata storage will be shared. The issue you are propably facing is described here https://github.com/typestack/class-validator/issues/181#issuecomment-375466913.

> The other method is if you are in control of some-package then you can specify a range instead of an explicit version in both package like 0.x (^0.8 won't work here, because we are below 1.x so minors are considered major by npm). This will flattern you dependencies if you use the latest at least npm@5.x into this:

```
- node_modules
  - some-package (requires class-validator@0.x)
  - class-validator (class-validator@0.x used by both package)
- app.ts (requires class-validator@0.x)
```
So you need to pin the same version or use the same version range across all project.

I will go ahead and close this, if you have any more question feel free to continue the discussion.

**Comment by frco9** [comment]
I'd like to perform some "complex" transformation requiring dependency injection. The idea is really similar to https://github.com/nestjs/nest/issues/528 
I'm using `class-transformer` with `nestjs` and `typeORM` and I'd like to get access to a `Repository` inside a `transform` in order to get data from DB for transformation. 

The use case would be to achieve something similar to [DRF SlugRelatedField](https://www.django-rest-framework.org/api-guide/relations/#slugrelatedfield)
