### ISSUE TITLE
Class to another class (type-safe)

### ISSUE THREAD

**Issue by jcudzich** [typestack/class-transformer#157]
Hello,

I would like to map one class to another, is there any solution to use `@Expose()` decorator in type-safe way? Example:

Map `User` class...

```
class User {
  id: number;
  email: string;
  name: string;
  password: string;
}
```

 ...to `UserVm` class:
```
@Exclude();
class UserVm {

  @Expose((model: User) => model.email)
  email: string;

  @Expose((model: User) => model.name)
  name: string;

}
```

I don't want use `@Expose({ name: 'email' })` because when I change property name in User class I would like to see type error in UserVm class.
I know that is option like:

```
@Transform((value, model: User) => model.email, { toClassOnly: true })
``` 
But I think about shorter replacement.

**Comment by MTschannett** [comment]
In my understanding Expose is a decorator to expose and when needed rename a property when it gets changed by class-transfomer.

What you are trying to do is to map a object to another based on its property, which isn't what `exclude` tries to achieve.

**Comment by MTschannett** [comment]
I'll close this issue because of inactivity. If further discussion is needed, feel free to reopen this issue or create a new one.

**Comment by Can-Sahin** [comment]
I would like to open again. 

The problem is let say there is an object
```typescript
class User {
	name: string;
}
```

and you are transforming it into

```typescript
class UserDto {
  	@Expose({name: 'name'})
	firstname: string;
}
const dto = plainToClass(UserDto, userObj);
```

This works. However this cannot be **refactored**. When you change User's `name` into another thing you have to update `@Expose` too and compiler will not warn you to do. 

When the project is growing there are lot of refactoring happening and you loose track of what to change and since its not fully type-safe, typescript doesn't warn you. 

This issue's request is a valid request I think. Mapping objects with **refactorable** way is something I need very often!
