### ISSUE TITLE
Using moment with class-transformer

### ISSUE THREAD

**Issue by tstavinoha** [typestack/class-transformer#176]
Hello, 

I'm trying to convert a literal object with a propery of type Moment (from moment.js) to a class instance. However trying to do so causes an error: `Cannot read property '_isAMomentObject' of undefined`.

I've tried setting the @Transform decorator on the field but it doesn't get called at all, probably due to error occurring before it.

I've tracked the debugger to a line in TransformOperationExecutor where it tries to instantiate a
`new targetType();`, where target type looks like a function that accepts one argument. That argument is undefined once Moment.js starts its copyConfig function, thus causing an exception.

What causes this and how to get around it?

Here is an example: https://codesandbox.io/s/zrn7yor7o4

```
class Test {
  public value: string;

  @transformer.Transform(value => {
    console.log("Transforming: ", value);
    return value;
  })
  public date: moment.Moment;
}

const plain: Test = { value: "yes", date: moment() };

console.log(plain);
console.log(transformer.plainToClass(Test, plain));
```

**Comment by cojack** [comment]
@tstavinoha your code works but with one simple change, you can not pass moment() object as a plain javascript object, because he is not. So to achieve your goal, you have to use string that represents a date in some moment od Date format, then you can transform it by `@Transform` decorator to the moment object.

so instead of: 

```typescript
const plain: Test = { value: "yes", date: moment() };
```

pass: 

```typescript
const plain: Test = { value: "yes", date: "2018-10-21T11:43:23.534Z" };
```

I'm closing this issue, because it works.
