### ISSUE TITLE
fix: @Exclude and other decoratos are not found during classToPlain

### ISSUE THREAD

**Issue by NoNameProvided** [typestack/class-transformer#199]
The issue is detailed/discussed in #106. 

@emlynmac, @nolazybits, @VMois, @akki-jat can any of you provide a minimal reproducible code example via [stackblitz](https://stackblitz.com/)?

**Comment by tempofeng** [comment]
@NoNameProvided I'm not sure if I'm running into the same issues as other, but I have create a minimal reproducible code here:
https://github.com/tempofeng/class-transformer-issue

I have created two tests to demo how plainToClass is ignoring annotations in routing-controllers.
Please take a look!

**Comment by akki-jat** [comment]
Hi, @NoNameProvided, I have solved the problem which was causing the transform issue.

### Issue (in my case)
I was doing plainToClass & after that I was doing Object.assign & because of that classToPlain was not able to transform class correctly.
I think because Object.assign creates the copy of object & becasue of that classToPlain was not able to get reflect data.

And I think it will great to transform class event after Object.assign.

**Comment by akki-jat** [comment]
@NoNameProvided here is the link to see that it is not working when doing Object.assign

### Link
[https://codesandbox.io/s/04w4nrp8vw](https://codesandbox.io/s/04w4nrp8vw)

**Comment by akki-jat** [comment]
@NoNameProvided any comment on this?

**Comment by wfrank2509** [comment]
Is there any plan how that can be solved and suggestion for a PR/Fix I could try to make?

**Comment by NoNameProvided** [comment]
These issues are caused by the class-transformer not having any registered metadata for the transformed object. These scenarios will be "solved" by #384.
