### ISSUE TITLE
NPM version used in the package

### ISSUE THREAD

**Issue by guscastro** [typestack/class-transformer#218]
I'm trying to make some contributions to fix some issues I have found, but I've downloaded the repository and run `npm install` and I'm getting a wildly different `package-lock.json`.

Which version of NPM are you using to generate the current `package-lock.json`?

I have particularly noticed that the versions in the lockfile aren't locked (i.e.: they depend on caret `^` versions) and that some tarballs are pointing at plaintext `http` endpoints.

**Comment by NoNameProvided** [comment]
Hi @guscastro!

After installing the latest NPM CLI, you can use the `npm ci` command to install dependencies from the `package-lock.json`. This way you will have the exact same dependencies what was used to compile the project at the latest release.

> Which version of NPM are you using to generate the current package-lock.json?

Mine is 6.6.0 but bigger is the better here ;) 

> I have particularly noticed that the versions in the lockfile aren't locked (i.e.: they depend on caret ^ versions)

Only the `requires` parts have caret which is fine because that is used to create the dependency graph, but the actually installed versions are always locked to a specified version. (Eg `A` requires `X@^1.2.0` and `B` requires `X@1.3.4` then `X@1.3.4` will be installed and it's `version` will be explicitly locked to that version.

>  and that some tarballs are pointing at plaintext HTTP endpoints.

It's okay because every tabarll has a hash is included, so the NPM CLI will detect if any funny business is going on.
