### ISSUE TITLE
Transformer order is inconsistent

### ISSUE THREAD

**Issue by jbdemonte** [typestack/class-transformer#231]
The execution order of the transformers should always be the same.
It seems to be reverse each time it's used

```
    class TestDto {
      @Expose()
      @Transform(() => console.log('A'), { toClassOnly: true })
      @Transform(() => console.log('B'), { toClassOnly: true })
      @Transform(() => console.log('C'), { toClassOnly: true })
      value: string;
    }

    for (let i = 0; i < 4; i++) {
      console.log(`--- Loop ${i} ----`);
      plainToClass(TestDto, {});
    }
```

This test log:
```
--- Loop 0 ----
A
B
C
--- Loop 1 ----
C
B
A
--- Loop 2 ----
A
B
C
--- Loop 3 ----
C
B
A
```

**Comment by VinceOPS** [comment]
This is probably due to:

```typescript
return (metadataFromAncestorsTarget).reverse().concat((metadataFromTarget || []).reverse());
```

in `MetadataStorage#findMetadatas`, called by `MetadataStorage#findTransformMetadatas`.

And is indeed a bug. @247GradLabs any clue regarding the reason of these calls to `reverse`? Thanks a lot!

**Comment by alexpls** [comment]
@VinceOPS Indeed. I think the order should be reversed so the transformers get applied in the correct order, but since `Array.prototype.reverse()` mutates the array it's called on, every time that code is run the array switches ordering.

I'd be happy to work on a PR to fix this, once this package is under active maintenance again.

**Comment by kirit0s** [comment]
This bug made my day. Apparently, this bug is not critical for open source.
