### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by johndoe2361289638165** [typestack/class-transformer#236]
Is there any new release planned in the near future? Thx

**Comment by johannesschobel** [comment]
it would be helpful to tag the current `develop` branch as a new version as well.. Because - for example - the current version does not support the `ClassTransformOption.excludeExtraneousValues` property, which is already mentioned in the docs..

Maybe someone can tag / release a new version? Thanks a lot!

**Comment by yesworld** [comment]
Please release a new version. Thanks guys for your work! :1st_place_medal:

**Comment by triptec** [comment]
I'm also in need of ClassTransformOption.excludeExtraneousValues

**Comment by alexpls** [comment]
We're depending on a new release as well in order to move away from our `class-transformer` fork and back onto mainline, specifically for https://github.com/typestack/class-transformer/pull/197.

@NoNameProvided (tagging you as you seem to be the most active maintainer) - do you know if this repository is currently being maintained? If not, it would be good to put out a request for maintainers so that we can cut down on some of the open PRs/issues.

**Comment by keenondrums** [comment]
@NoNameProvided @19majkel94 any chance you could publish a new release?

**Comment by ddrozdov** [comment]
@MTschannett is this project still alive?

**Comment by DusanDimitric** [comment]
A new release would be appreciated!

We need `ClassTransformOption.excludeExtraneousValues`.

Thanks!

**Comment by Dzhekson6000** [comment]
@triptec @DusanDimitric 
Use
`plainToClass(User, fromPlainUser, { strategy: 'excludeAll' });`
this is an alternative

**Comment by DusanDimitric** [comment]
@Dzhekson6000 
Unfortunately that is not the same thing. It does not solve the problem.

We still need a release!

**Comment by kirushi** [comment]
+1 on needing ClassTransformOption.excludeExtraneousValues.

Looking forward to the release :)

**Comment by signal-intrusion** [comment]
@NoNameProvided @19majkel94 

How can I help you publish a new release to npm?

**Comment by triptec** [comment]
Seems it might be time to look for someone willing to maintain a fork and publish under another name on npm?

**Comment by NoNameProvided** [comment]
Hi all! 

Damn, I have seen this sadly only now. 🙁 But I made a new release now from the current develop branch as `0.2.1` which includes the `excludeExtraneousValues` option! 

The reason I have seen this only now is that I am still busy with other things (and it seems the other recently added contributors as well) and due to this sadly I have like 400+ notification which I hope once I can answer. So it's pretty hard for me to spot the issues where "administration" action is needed.

Actually releasing a new version is like five minutes, so this really a bummer for me, sorry again. 🙁 I have mentioned this a few time, but I am saying here again feel free to reach out for me on [Twitter](https://twitter.com/NoNameProvided_) because I use it on a daily basis. (So if you reply to this and I don't answer when you expect it ping me.)

> How can I help you publish a new release to npm?

After the recent NPM fiascos, I don't feel confident adding new NPM publishers, but we can totally automate this with Travis, so if anyone can make a PR for that would be wonderful. (Ping me and it gets merged)

**Comment by NoNameProvided** [comment]
Also, a pinky promise that I will __try__ to go through the PRs this weekend. However, the "problem" with them is not related to the code itself but the approach we took. (If we just keep merging overlapping features that will just create more and more confusion about the usage.)

**Comment by triptec** [comment]
Thank you.

**Comment by johannesschobel** [comment]
Good to have you back :)
