### ISSUE TITLE
Feature: overwrite metadata with targetMaps

### ISSUE THREAD

**Issue by haschu** [typestack/class-transformer#265]
Consider the following use case:

```ts
class Happy {
   
  @Type(() => HappyFeeling)
  feeling: HappyFeeling

}
```

The following wouldn't work:

```ts
const happy = plainToClass( Happy, ..., {
 targetMaps: {
    target: Happy,
    properties: {
      feeling: SuperHappyFeeling
    }
  }
});

happy.feeling // no instance of SuperHappyFeeling :(
```

as `feeling` is already defined by `@Type`. But sometimes it would be useful, if we could overwrite the `@Type` definition with `targetMaps`.

What do you guys think about that feature? I would submit a PR if you're okay with it :)

**Comment by NoNameProvided** [comment]
Hi @haschu! 

Sorry for the late reply and thanks for the proposal. We are moving away from allowing `targetMaps` to be defined so we won't accept a contribution to this. 

If you feel this is a must-have feature please comment your use-case and rationale of why do you prefer this approach instead of others and I will reopen to discuss. Thanks!

**Comment by haschu** [comment]
Hi @NoNameProvided.

To be honest, I don't really know what this is about anymore... :sweat_smile:

But thanks for your answer anyways!
