### ISSUE TITLE
question: interface in constructor with plainToClass

### ISSUE THREAD

**Issue by eddievagabond** [typestack/class-transformer#300]
Is something like this possible through this library. I've looked through the docs and issues and couldn't find anything. Although I may be missing something.
```ts
export interface IUser {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
}

export class UserOnboarding extends User {
  @IsNotEmpty({
    message: 'Please enter a valid password.'
  })
  public password: string;

  constructor(userOnbarding: IUser) {
    super(userOnbarding);
    this.password = userOnbarding.password;
  }
}

plainToClass(UserOnboarding, {
  firstName: '',
  lastName: '',
  emaiL '',
 password: ''
});
```

**Comment by NoNameProvided** [comment]
Can you detail your question a little more? What is the desired functionalty here exactly? 

What you try to do in the currently provided snippet is impossible because you cannot `extend` a `class` with an `interface`, you can only `implement` it. If you meant that, maybe this question about inheritance? We do support it, so if you extend a class that has decorators defined on it's properties it will be transformed by the library.

**Comment by NoNameProvided** [comment]
Closing, no response.
