### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by yedlosh** [typestack/class-transformer#314]
Hi, this is now quite an important library to our project, so it is worrying to see that no commits are being made, no PRs are getting merged, everything's waiting for a review..

Is this alive? Could be new reviewers promoted so stuff can get merged?

AFAIK there is no other major TS library which fully do what class-transformer/class-validator are capable of, so it would be very sad to see this repo wither. 
Tell me if I'm wrong, I'd be happy to have a look at the others (and be calmer knowing there is a fallback)

Cheers!

**Comment by souravsaraf** [comment]
I am also looking for a library which does the serilization and deserialization of json into typescript objects (of type class with functions) and vice versa.

So far, I came across <a href = "https://github.com/weichx/cerialize">cerialize</a> , <a href = "https://github.com/JohnWeisz/TypedJSON">TypedJSON</a> and this one itself (<a href="https://github.com/typestack/class-transformer">class-transformer</a>) . 

Looks like , out of above 3 only TypedJSON is active.
Does anyone have any suggestions on which library to use?

Thanks

**Comment by cristianmiranda** [comment]
I used to use json2typescript, then met class-transformer and now I switched to TypedJSON (hopefully for good). I'm not saying the first two are bad, but I ran into some parsing issues that required me to change the way I did things. TypedJSON seems to be very lightweight and non intrusive.

**Comment by marcj** [comment]
Guys, I got you covered. There's [Marshal.ts](https://github.com/marcj/marshal.ts), the fastest JS serializer on the planet thanks to the JIT engine. Up to 30500% faster (yes that's 300 times) than class-transformer and probably a couple of hundred times faster than mentioned serializers. Beside that it covers a lot of types like Enums, binary fields, constructor assignment, etc. On top of that I personally like that short decorator a lot more - and that you only have one of them, not dozens. A different marshal package comes with a handy MongoDB ORM abstraction and serialization target, as well as database query implementation, which of courses uses the fast Marshal core to serialize mongo records to class instances and vice-versa.
I use Marshal since years on a big projects (like https://deepkit.ai) and it's fair to say it works flawlessly. Take a look and let me know what you think.

**Comment by Syy0n** [comment]
I think this project is dead. Should be considered by nest.js, because they heavily depend on this project.

**Comment by danielweck** [comment]
TA-JSON is good too:
https://github.com/edcarroll/ta-json

**Comment by pichillilorenzo** [comment]
You can take a look and try also my library [`jackson-js`](https://github.com/pichillilorenzo/jackson-js), which has a lot of decorators and features to easily manipulate JSON, including class transformation as this one. Class transformation is only a little part of what my library can do! As the name implies, it is heavily inspired by the famous Java [FasterXML/jackson library](https://github.com/FasterXML/jackson) and implements almost all of the Java Jackson annotation!

**Comment by jotamorais** [comment]
Hi, 

This project is very much alive.
I recently posted an issue and pinned to each of the TypeStack repos, asking for the community help with issue triage, suggestions and also new maintainers.

I'm closing this issue in favor of https://github.com/typestack/class-transformer/issues/360

Thank you!
