### ISSUE TITLE
Using classes from external library

### ISSUE THREAD

**Issue by frankps** [typestack/class-transformer#337]
I'm using this library for a long time with success, but...

But since I refactored my code, it doesn't want to work anymore: I moved all my (model) classes to an external Typescript library (npm package). 

So now I have my Angular project that imports my model-library and apparently class-transformer doesn't support this (?). Only the root classes are typed correctly, all sub-property classes are NOT typed anymore (just Object).

Example:
```
class Order {
  @Type(() => Customer)
  customer: Customer

  @Type(() => OrderLines)
  lines: OrderLines
}
```

If I get back an order from my back-end, then
   order is of type Order  
but:
   order.customer is of type Object
   order.lines is of type Object[]

Does anybody have experience with class-transformer and separate libraries (packages)?
Thx!!

**Comment by jamesmikesell** [comment]
I ran into the same problem.

My current hack to get around this, my "model-library" project has a utility class with methods to do the `plainToClass()` conversions.

Example
```typescript
//this file is defined in my shared model library project
export class CommonTransformer {
  static plainToClassSingle<T, V>(cls: ClassType<T>, plain: V, options?: ClassTransformOptions): T {
    return plainToClass(cls, plain, options);
  }
}
```

Then in my angular project, when i need to convert JSON objects received from the server:
```typescript
//this file is defined in angular

    this.http.get<TableAndHand>("/api/getOrder")
      .toPromise()
      .then(order => {
        order = CommonTransformer.plainToClassSingle(Order, order);
        //..............
      });
```

I'd love to find a more elegant solution, but in the meantime the above seems to work.

**Comment by frankps** [comment]
Thx for your input!! That could be a work-around for me too! I give it a try...

**Comment by massimodeluisa** [comment]
Beautiful work-around! Thank @jamesmikesell !!!

**Comment by RW-DiefBell** [comment]
Would this work the other way around? I'm calling plainToClass inside my library, which causes the same issue...

**Comment by ukarlsson** [comment]
I had what seems to be exactly the same issue with marshal.ts and got a very good overview of the issue with a few suggested solutions, please see

https://github.com/super-hornet/super-hornet.ts/issues/52

**Comment by NoNameProvided** [comment]
This is most likely because your dependencies are not flattened and your main code and the external code uses a different version of the library. So your `node_modules` should look something like this: 

```
node_modules\
  - external_lib\
    - some-code.js
    - node_modules\
      - class-transformer\
  - class-transformer\
your-main-code.js
```

Because of this structure 
- the extrenal lib will load class-transformer from `node_modules\external_lib\node_modules\class-transformer`
- your main code will load it from `node_modules/class-transformer`

This means the metadata is stored in the extnernal lib's class-validator and you are trying to transform via your main class-validator instance which doesn't know anything about the operators and classes you have created.

To fix this, make sure your node_modules folder contains exactly one `class-validator` folder.

**Comment by NoNameProvided** [comment]
Closing as solved if the issue persist, feel free to continue the discussion here and I will re-open.
