### ISSUE TITLE
Running plainToClass in external library not working

### ISSUE THREAD

**Issue by RW-DiefBell** [typestack/class-transformer#359]
So I want users to be able to define their own classes in their projects then for my library to run plainToClass with them, however it just makes a copy of the plain object instead of properly transforming it. The transformation works fine if the class is in the library, but obviously this isn't useable by an end-user. It's essentially the opposite problem to #337 .

In my library
```typescript
public static async GetByName<Q>(name : string, classType : (new(args : any[]) => Q))
{
    const res = await Axios.post(API_ENDPOINT, {
        APIKey: process.env.API_KEY,
        Action: "GetQueryResultByQueryName",
        QueryName: name
    });

    const queryResponse = res.data;

    const queryData = plainToClass(classType, queryResponse);
    debug(queryData[0]); // shows that it's just a copy of the plain objects in res.data
    
    return new Query<Q>(queryData);
}
```

Example code for a project using this library:
```typescript
export class TestPayrollReportMonthlyQuery
{
    /** Query Data **/
    @Expose({ name: "Employee Id" })
    employeeId : string;

    @Expose({ name: "Assignment Date" })
    @Type(() => Date)
    assignmentDate : Date;

    @Expose({ name: "Assignment Start Time" })
    @Type(() => Time)
    assignmentStartTimeRaw : Time;

    @Expose({ name: "Assignment Total Hours" })
    @Transform((hours) => hours + ":00")
    assignmentTotalHours : string;
}
```

Is there something obvious I'm doing wrong, or a work around that I could use? I know that this is the exact functionality implemented in TypeStack Routing Controllers so it must work somehow...

Thank you very much for your help :)

**Comment by Goodluckhf** [comment]
It works like this because your lib and _code for a project using this library_ has different metadata storage. There are several things you can do to fix it
- export these decorators (Expose, Transform) from your lib, ofc it's not convenient 
- install `class-transformer` in your lib as peer dependency

**Comment by RW-DiefBell** [comment]
@Goodluckhf I'm already using it as peer dependencies. Is it possible that it's something to do with using NPM Link?

Package.json in library:
```json
"dependencies": {
  "axios": "^0.19.2",
  "debug": "^4.1.1",
  "reflect-metadata": "^0.1.13"
},
"devDependencies": {
  "@types/node": "^14.0.12",
  "dts-bundle-generator": "^4.3.0",
  "prettier": "^2.0.5",
  "tslint": "^6.1.2",
  "typescript": "^3.9.5",
  "class-transformer": "^0.2.3",
  "class-validator": "^0.12.2"
},
"peerDependencies": {
  "class-transformer": "^0.2.3",
  "class-validator": "^0.12.2"
}
```

**Comment by RW-DiefBell** [comment]
Update: Uninstalling class-transformer (and class-validator) then re-installing them in my main project has fixed the issue. I believe that I installed them _before_ linking my library, and therefore it didn't link their metadata storage as expected. Will continue to test then will close the issue once I believe that this is the correct fix.

**Comment by fhebuterne** [comment]
Someone has given a solution on this issue https://github.com/typestack/class-transformer/issues/313 adding class-transformer nodemodules path in tsconfig work for me.

**Comment by RW-DiefBell** [comment]
@fhebuterne is that in the lib's tsconfig? Or the main project that uses the lib?

**Comment by fhebuterne** [comment]
> @fhebuterne is that in the lib's tsconfig? Or the main project that uses the lib?

On the main project

**Comment by RW-DiefBell** [comment]
That feels a bit hacky? I don't have to do that if I'm using something like Routing Controllers. Is this whole issue just some kind of bug?

**Comment by fhebuterne** [comment]
> That feels a bit hacky? I don't have to do that if I'm using something like Routing Controllers. Is this whole issue just some kind of bug?

Hmm, i don't know, i think you right, it not very clean solution but i needed quick fix if someone has better solution, i take it.

**Comment by NoNameProvided** [comment]
This is most likely because your dependencies are not flattened and your main code and the external code uses a different version of the library. So your `node_modules` should look something like this: 

```
node_modules\
  - external_lib\
    - some-code.js
    - node_modules\
      - class-transformer\
  - class-transformer\
your-main-code.js
```

Because of this structure 
- the extrenal lib will load class-transformer from `node_modules\external_lib\node_modules\class-transformer`
- your main code will load it from `node_modules/class-transformer`

This means the metadata is stored in the extnernal lib's class-validator and you are trying to transform via your main class-validator instance which doesn't know anything about the operators and classes you have created.

To fix this, make sure your node_modules folder contains exactly one `class-validator` folder.

**Comment by NoNameProvided** [comment]
Closing as solved if the issue persist, feel free to continue the discussion here and I will re-open.
