### ISSUE TITLE
fix: @Expose() decorator not working for object imported in another package

### ISSUE THREAD

**Issue by lucafaggianelli** [typestack/class-transformer#394]
### Description

A class property decorated with `@Expose()` is not exposed when the object is imported in another package

**Minimal code-snippet showcasing the problem**
 

```ts
// node package `plugins`
// this package is a node library with its own tsconfig.json
class Credentials { }

class OAuth2Credentials extends Credentials {
  @Expose()
  get authUrl () {
    return `${this.baseAuthUrl}/something`
  }
}

export const credentials: Credentials[] = [ /* full of creds */ ]
// succeeds
assert(classToPlain(credentials[0]).authUrl)
```

```ts
// node package `main`
import { credentials } from 'plugins'
import { classToPlain } from 'class-transformer'

// fails
assert(classToPlain(credentials[0]).authUrl)
```

### Expected behavior

I expect to see the exposed property

### Actual behavior

The exposed property is not there

**Comment by NoNameProvided** [comment]
Hi! 

Can you verify that only a single version of class-transformer exists in your `node_modules`?

This is most likely because your dependencies are not flattened and your main code and the external code uses a different version of the library. So your `node_modules` should look something like this: 

```
node_modules\
  - external_lib\
    - some-code.js
    - node_modules\
      - class-transformer\
  - class-transformer\
your-main-code.js
```

Because of this structure 
- the extrenal lib will load class-transformer from `node_modules\external_lib\node_modules\class-transformer`
- your main code will load it from `node_modules/class-transformer`

This means the metadata is stored in the extnernal lib's class-validator and you are trying to transform via your main class-validator instance which doesn't know anything about the operators and classes you have created.

To fix this, make sure your node_modules folder contains exactly one `class-validator` folder.

**Comment by lucafaggianelli** [comment]
thank you so much! yes that's exactly my case, though the situation is more complex because I'm linking the packages, basically I have a monorepo with multiple packages:

```
my-app/
  server/
    package.json
    node_modules/
      plugins/ (symlink to ../../plugins/ folder)

  plugins/
    package.json
    node_modules/
      class-transformer
```

In this scenario it's not possible to remove 1 of the 2 `class-transformer` packages, maybe using Learna I could fix the issue as it installs all packages' dependencies in 1 unique node_modules folder... do you have other ideas?

**Comment by NoNameProvided** [comment]
Make sure you have the same version of `class-transformer` defined in all your `package.json`s and run `lerna bootstrap` after. It should extract a single version of `class-transformer` to `node_modules` folder in the project root. 

I am closing this issue as solved. If you still experience some issues please comment and I will reopen.

**Comment by lucafaggianelli** [comment]
OK I ended up using [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/), a light version of lerna and it's working, I just have 1 version of class-transformer.

Thanks a lot for your help!
