### ISSUE TITLE
question: How to transform response DTO?

### ISSUE THREAD

**Issue by Tam2** [typestack/class-transformer#555]
I have created a response DTO for my controller (have done this because i want different columns in different responses so i haven't added to the entity)

```ts
export class InventorySearchResponseDTO {
  vehicles: UsedVehicleSearchResponse[];
  cursor: Cursor;
}

export class UsedVehicleSearchResponse {
  id: number;
  make: string;

  @Exclude()
  clientId: number;

  @Type(() => Model)
  @Transform((model) => model.name)
  model: Model;
}
```

Then within my service, I'm setting the response type to `InventorySearchResponseDTO`

```ts
  async search(
    clientId: number,
    query: InventorySearchRequestDTO,
  ): Promise<InventorySearchResponseDTO> {
    const { data, cursor } = await this.usedVehicleRepository.searchInventory(
      clientId,
      query,
    );

    return {
      vehicles: data,
      cursor: cursor,
    };
  }
```

I have the ClassSerializerInterceptor enabled globally 

`app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));`

**The problem:**

When the request is sent back to the user it doesn't appear to be transforming the response, based on the above DTO, i would expect it to remove the clientId and transform the model to just model.name

```json
{
  "vehicles": [
    {
      "id": 1220,
      "clientId": 12,
      "modelId": 17,
      "variant": "2 ISG",
      "price": 18999,
      "model": {
        "id": 17,
        "name": "Sportage",
        "makeId": 5,
        "vehicleType": 1,
        "slug": "sportage",
        "make": {
          "id": 5,
          "name": "Kia",
          "slug": "kia",
          "franchise": false,
        }
      },
      "make": "Kia"
    }
  ],
  "cursor": {
    "afterCursor": "aWQ6MTk1MQ==",
    "beforeCursor": null
  }
}
```

**Comment by Tam2** [comment]
Tried adding @Type but it still doesn't work

```
export class InventorySearchResponseDTO {
  @Type(() => UsedVehicleSearchResponse)
  vehicles: UsedVehicleSearchResponse[];
  cursor: Cursor;
}
```

**Comment by AckerApple** [comment]
Your original code was correct but breaking changes were introduced in version 0.3.2

Please review top issues here that many of us our pitching in to alert others about

**Comment by NoNameProvided** [comment]
Your first example doesn't work because I assume the passed response is an object matching the interface of your class but for `class-transformer` to work, the object must be an instance of the class. (I cannot say for sure because the implementation of `this.usedVehicleRepository.searchInventory` is not included.)

In your second example you make your object a class instance without calling the constructor. I would just suggest to call `plainToClass` on the objects when you request them in the `searchInventory` function.

Also probably you want to update your model to simplify the model in to plain transformations only: 

```
@Type(() => Model)
@Transform(({ value }) => value.name, { toPlainOnly: true })
model: Model;
```
